/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITimelockVault,
  ITimelockVaultInterface,
} from "../../../contracts/RaffylFactory.sol/ITimelockVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "tos",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "batchPay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITimelockVault__factory {
  static readonly abi = _abi;
  static createInterface(): ITimelockVaultInterface {
    return new Interface(_abi) as ITimelockVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITimelockVault {
    return new Contract(address, _abi, runner) as unknown as ITimelockVault;
  }
}
