/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  RaffleHelpers,
  RaffleHelpersInterface,
} from "../../../contracts/libraries/RaffleHelpers";

const _abi = [
  {
    inputs: [],
    name: "NoWinners",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122088259ed370fc9e2caa2aa1dd502a6005e9020665e3d6e822d72e6037e1aafe8064736f6c634300081c0033";

type RaffleHelpersConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RaffleHelpersConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RaffleHelpers__factory extends ContractFactory {
  constructor(...args: RaffleHelpersConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RaffleHelpers & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RaffleHelpers__factory {
    return super.connect(runner) as RaffleHelpers__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RaffleHelpersInterface {
    return new Interface(_abi) as RaffleHelpersInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RaffleHelpers {
    return new Contract(address, _abi, runner) as unknown as RaffleHelpers;
  }
}
