/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICommunity__factory } from "./ICommunity__factory";
export { IRaffle__factory } from "./IRaffle__factory";
