/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRaffylFactory,
  IRaffylFactoryInterface,
} from "../../../contracts/Community.sol/IRaffylFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "onRaffleCreated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "processBatchPayout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRaffylFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IRaffylFactoryInterface {
    return new Interface(_abi) as IRaffylFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRaffylFactory {
    return new Contract(address, _abi, runner) as unknown as IRaffylFactory;
  }
}
